@startuml OODProject
title OODProject

Class Main {

}


Class Product {

}

Class Material {

}

Class ImpactCalculationStrategy {

}

Class RecyclingGuidance  {
    
}

Class RecyclingCategory {

}

Class LoginManager {

}

Class Account {

}

Product"1" *-- "1..*"Material
Product --> ImpactCalculationStrategy : uses
Product --> RecyclingGuidance : uses
Material --> ImpactCalculationStrategy : uses
LoginManager "1" *-- "0..*" Account
RecyclingGuidance --> RecyclingCategory : uses
Material"1..*" o-- "1" RecyclingCategory
@enduml