/*
 * This source file was generated by the Gradle 'init' task
 */
import java.util.Scanner;
import g1.presentation.*;

public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        MaterialMenu materialmenu = new MaterialMenu(scanner);
        materialmenu.run();
        System.out.println("Returned to Main");
        scanner.close();


    }
}
