

/*
 * This source file was generated by the Gradle 'init' task
 */

import g1.presentation.ConsoleUi;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ConsoleUi console = new ConsoleUi();
        console.runMenu();
        



        
        // readFromFileProduct()

        //return arraylist

        //MaterialApplicationService mas = new MaterialApplicationService(readFromFileProduct()) 
        
        
        //readFromFileMaterial()
        //readFromFileAccount()
    }
}
