/*
 * This source file was generated by the Gradle 'init' task
 */
import java.util.Scanner;

import g1.presentation.AccountMenu;
import g1.presentation.AdminMenu;
import g1.presentation.LoginMenu;
import g1.presentation.MaterialMenu;
import g1.presentation.productMenu;
import g1.presentation.userMenu;


public class App {
    public String getGreeting() {
        return "Hello World!";

    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        
        MaterialMenu materialmenu = new MaterialMenu(scanner);
        productMenu productMenu = new productMenu(scanner);
        AccountMenu accountMenu = new AccountMenu(scanner);
        AdminMenu adminMenu = new AdminMenu(scanner, materialmenu, productMenu, accountMenu);
        userMenu userMenu = new userMenu(scanner, materialmenu, productMenu);
        LoginMenu loginMenu = new LoginMenu(scanner, adminMenu, userMenu);
        loginMenu.runMenu();

        scanner.close();


    }
}
